FirstApp/urls.py
from django.conf.urls import url
from django.urls import path
from FirstApp import views


app_name='FirstApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/', views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album_list/<pk>/', views.album_list, name='album_list'),
    path('edit_artist/<pk>/', views.edit_artist, name='edit_artist'),
    path('edit_album/<pk>/', views.edit_album, name='edit_album'),
    path('delete_album/<pk>/', views.delete_album, name='delete_album'),
    path('delete_artist/<pk>/', views.delete_artist, name='delete_artist'),


]

my_first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('FirstApp.urls')),
]

FirstApp/models.py
from django.db import models

# Create your models here.
class Musician(models.Model):
    #id=models.AutoField(Primary_key=True) #django set it autometically if we not set it
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    instrument = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name}  {self.last_name}'

class Album(models.Model):
    artist= models.ForeignKey(Musician,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    release_date = models.DateField()
    rating = (
    (1,'worst'),
    (2,'bad'),
    (3,'Not bad'),
    (4,'good'),
    (5,'Excellent')
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return f'{self.name}   -   Rating: {self.num_stars}'

FirstApp/forms.py
from django import forms
from django.core import validators
from FirstApp.models import Musician,Album

#creating form......Each form like as class
class MusicianForm(forms.ModelForm):
    class Meta:
        model = Musician
        fields ='__all__'

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = Album
        fields = '__all__'

FirstApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from FirstApp.models import Musician, Album
from FirstApp import forms
from django.db.models import Avg

# Create your views here.

def index(request):
    musician_list=Musician.objects.order_by('first_name')
    dict={'title':"Home Page",'musician_list':musician_list}
    return render(request,'FirstApp/index.html',context=dict)

def album_list(request,pk):
    artist_info = Musician.objects.get(pk=pk)
    album_info = Album.objects.filter(artist_id=pk).order_by('name')
    artist_rating = Album.objects.filter(artist_id=pk).aggregate(Avg('num_stars'))
    dict={'title':'List of Album','artist_info':artist_info,'album_info':album_info,'artist_rating':artist_rating}
    return render(request,'FirstApp/album_list.html',context=dict)

def musician_form(request):
    form=forms.MusicianForm()
    if request.method == 'POST':
        form=forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
    dict={'title':'Add Musician','form':form}
    return render(request,'FirstApp/musician_form.html',context=dict)

def album_form(request):
    form = forms.AlbumForm()
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
    dict={'title':'Add Album','form':form}
    return render(request,'FirstApp/album_form.html',context=dict)

def edit_artist(request,pk):
    artist_info = Musician.objects.get(pk=pk)
    form = forms.MusicianForm(instance=artist_info)
    if request.method  == 'POST':
        form = forms.MusicianForm(request.POST,instance=artist_info)
        if form.is_valid():
            form.save()
            return album_list(request,pk)

    dict={'form':form,'artist_info':artist_info}
    return render(request,'FirstApp/edit_artist.html',context=dict)

def edit_album(request,pk):
    album_info = Album.objects.get(pk=pk)
    form = forms.AlbumForm(instance=album_info)
    dict={'title':'Edit Album','form':form,'album_info':album_info}
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST,instance=album_info)
        if form.is_valid():
            form.save()
            dict.update({'success':'Album is Updated Successfully !'})
    return render(request,'FirstApp/edit_album.html',context=dict)


def delete_album(request,pk):
    album = Album.objects.get(pk=pk).delete()
    dict={'title':'Delete Album','delete':'Album is deleted Successfully !'}
    return render(request,'FirstApp/edit_album.html',context=dict)

def delete_artist(request,pk):
    artist = Musician.objects.get(pk=pk).delete()
    dict = {'title':'Delete Artist','delete':'Album is deleted Successfully !'}
    return render(request,'FirstApp/edit_artist.html',context=dict)

templates/FirstApp/album_form.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
<h3>Add Album:</h3>
<form method="POST">
  {{form.as_p}}
  <input type="submit" name="submit" value="ADD" class="btn btn-info">
  {% csrf_token %}

</form>


{% endblock %}

templates/FirstApp/album_list.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
<h2>List Of Album : </h2>
<h3>Name : {{artist_info.first_name}} {{artist_info.last_name}}</h3>
<h4>Instrument : {{artist_info.instrument}}</h4>
<h5>Artist Average Rating : {{artist_rating.num_stars__avg}}</h5>
<a href="{% url 'FirstApp:edit_artist' pk=artist_info.pk %}"  class="btn btn-primary">Edit</a>
<hr>
<h3>List of Album : </h3>
<table class="table table-striped" style='color:white'>
  <tr>
    <th>Album Name</th>
    <th>release_date</th>
    <th>Ratting</th>
    <th>Edit</th>

  </tr>
  {% for x in album_info %}
  <tr>

    <td>{{x.name}}</td>
    <td>{{x.release_date}}</td>
    <td>{{x.num_stars}}</td>
    <td><a href="{% url 'FirstApp:edit_album' pk=x.pk %}" style='color:white'>click here</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/FirstApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <style media="screen">
      body{
        background-image: url('{% static 'images/laptop.jpg' %}');
        background-repeat: no-repeat;
        background-size:cover;
        color: red;
      }
    </style>

    <title>{{ title }}</title>
  </head>
  <body >
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'FirstApp:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'FirstApp:musician_form' %}">Add Musician</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'FirstApp:album_form' %}">Add Album</a>
            </li>
          </ul>
        </nav>
        <div class="container">
          {% block body_block %}

          {% endblock %}

        </div>



  </body>
</html>

templates/FirstApp/edit_album.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
{% if success %}
<div class="alert alert-success">
  <h3>{{success}}</h3>

</div>
{% elif delete %}
<div class="alert alert-danger">
  <h3>{{delete}} </h3>

</div>
{% else %}
<form method="POST">
  {{form.as_p}}
  <input type="submit" name="submit" value="Update" class="btn btn-info">
  {% csrf_token %}
  &nbsp &nbsp &nbsp
  <a href="{% url 'FirstApp:delete_album' pk=album_info.pk %}" class="btn btn-danger" onclick="return confirm('Are You Sure Delete This Album ??')" >Delete</a>

</form>
<hr>


{% endif %}

{% endblock %}

templates/FirstApp/edit_artist.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
{% if delete %}
<div class="alert alert-danger">
  <h3>{{delete}}</h3>
</div>
{% else %}
<h1>Edit Artist : </h1>
<form  method="POST">
  {{form.as_p}}

  <input type="submit" name="submit" value="Update" class="btn btn-success">
   {% csrf_token %}
   &nbsp &nbsp
  <a href="{% url 'FirstApp:delete_artist' pk=artist_info.pk %}" class="btn btn-danger"
   onclick="return confirm('Are You Sure Delete This Artist ??')">Delete</a>
 </form>

{% endif %}
{% endblock %}

templates/FirstApp/index.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
<h1>Musicians: </h1>
<ul>
{% if musician_list %}

{% for x in musician_list %}
    <li><a href="{% url 'FirstApp:album_list' pk=x.pk %}">{{x.first_name}}&nbsp{{x.last_name}}</a></li>
{% endfor %}
{% else %}
<h3>No Musician in The List</h3>
{% endif %}
</ul>



{% endblock %}

templates/FirstApp/musician_form.html
{% extends 'FirstApp/base.html' %}
{% block body_block %}
<h2>Add Musician:</h2>
<form method="POST">
  {{form.as_p}}
  <input type="submit" name="submit" value="ADD" class="btn btn-info">
  {% csrf_token %}

</form>

{% endblock %}